name: First Workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Demo step
          run: echo "Welcome to GitHub Actions"

        - name: Checkout Repo
          uses: actions/checkout@v5

        - name: Install Cowsay
          run: sudo apt-get install cowsay -y

        - name: Create Dragon
          run: cowsay -f dragon "I am breathing fire" >> dragon.txt

        - name: Show Dragon
          run: cat dragon.txt

        