name: First Workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Demo step
          run: echo "Welcome to GitHub Actions"

        - name: Checkout Repo
          uses: actions/checkout@v5

        - name: List files
          run: ls

        - name: Print Readme
          run: cat README.md

        